#logger Config
logging.level.org.springframework=info
logging.level.com.cropdeal.CartPayService=debug

 
spring.application.name=cartservice
server.port= 8181
spring.data.mongodb.uri=mongodb://localhost:27017/test
spring.data.mongodb.database=CartService

