server.port=8082
spring.application.name=dealerservice
spring.cloud.config.enabled=false


spring.mvc.pathmatch.matching-strategy=ant-path-matcher

#db-config
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=DealerService
spring.data.mongodb.username=
spring.data.mongodb.password=
spring.data.mongodb.uri=mongodb://localhost:27017/test
spring.jpa.hibernate.ddl-auto=update


#logger Config
logging.level.org.springframework=info
logging.level.com.cropdeal.cropservice=debug


arshin.app.jwtSecret=arshinSecretKey
arshin.app.jwtExpirationMs= 86400000